"""Add recordings table

Revision ID: 17cd276f6a88
Revises: 0a3ffefc2683
Create Date: 2026-07-13 16:52:13.141650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cd276f6a88'
down_revision: Union[str, None] = '0a3ffefc2683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('provider_recording_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='ready', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("status IN ('ready', 'transcribing', 'transcribed', 'failed')", name='ck_recordings_status'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id')
    )
    op.create_index(op.f('ix_recordings_lesson_id'), 'recordings', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_recordings_provider_recording_id'), 'recordings', ['provider_recording_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_provider_recording_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_lesson_id'), table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
