"""Add Google OAuth fields to teachers and students

Revision ID: 1a7a5abeb6af
Revises: a5e28fe2bc54
Create Date: 2026-07-23 16:24:31.235100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7a5abeb6af'
down_revision: Union[str, None] = 'a5e28fe2bc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('auth_provider', sa.String(), server_default='password', nullable=False))
    op.add_column('students', sa.Column('google_sub', sa.String(), nullable=True))
    op.alter_column('students', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_students_google_sub'), 'students', ['google_sub'], unique=True)
    op.add_column('teachers', sa.Column('auth_provider', sa.String(), server_default='password', nullable=False))
    op.add_column('teachers', sa.Column('google_sub', sa.String(), nullable=True))
    op.alter_column('teachers', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_teachers_google_sub'), 'teachers', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_google_sub'), table_name='teachers')
    op.alter_column('teachers', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('teachers', 'google_sub')
    op.drop_column('teachers', 'auth_provider')
    op.drop_index(op.f('ix_students_google_sub'), table_name='students')
    op.alter_column('students', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('students', 'google_sub')
    op.drop_column('students', 'auth_provider')
    # ### end Alembic commands ###
