"""Add last_activity_at to lessons

Revision ID: 26cb4211fc5a
Revises: 38e6f1c35cd3
Create Date: 2026-07-22 23:19:54.851555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cb4211fc5a'
down_revision: Union[str, None] = '38e6f1c35cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'last_activity_at')
    # ### end Alembic commands ###
