"""Add transcript_chunks table

Revision ID: 38e6f1c35cd3
Revises: 17cd276f6a88
Create Date: 2026-07-13 17:02:51.934666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e6f1c35cd3'
down_revision: Union[str, None] = '17cd276f6a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_chunks',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset_seconds', sa.Float(), nullable=False),
    sa.Column('end_offset_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_transcript_chunks_lesson_start', 'transcript_chunks', ['lesson_id', 'start_offset_seconds'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_recording_id'), 'transcript_chunks', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_chunks_recording_id'), table_name='transcript_chunks')
    op.drop_index('ix_transcript_chunks_lesson_start', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    # ### end Alembic commands ###
