"""Add video room columns to lessons

Revision ID: 65e0d6db91bb
Revises: 79d179798310
Create Date: 2026-07-07 22:22:22.218524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e0d6db91bb'
down_revision: Union[str, None] = '79d179798310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_room_id', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('video_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_provider')
    op.drop_column('lessons', 'video_room_id')
    # ### end Alembic commands ###
