"""Add materials table

Revision ID: 6d010df2f12e
Revises: 0a3ffefc2683
Create Date: 2026-07-22 23:12:59.214141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d010df2f12e'
down_revision: Union[str, None] = '0a3ffefc2683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_materials_class_id'), 'materials', ['class_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_class_id'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
