"""Initial schema

Revision ID: 79d179798310
Revises: 
Create Date: 2026-07-05 19:57:59.086787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d179798310'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alert_threshold', sa.Numeric(precision=3, scale=2), server_default='0.50', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alert_threshold >= 0 AND alert_threshold <= 1', name='ck_classes_alert_threshold_range'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('current_skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mastery_level >= 0 AND mastery_level <= 1', name='ck_current_skills_mastery_range'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['skill_topics.topic_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('student_id', 'class_id', 'topic_id', name='uq_current_skills_student_class_topic')
    )
    op.create_index('ix_current_skills_class_topic', 'current_skills', ['class_id', 'topic_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_enrollments_student_class')
    )
    op.create_index('ix_enrollments_class_id', 'enrollments', ['class_id'], unique=False)
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'live', 'ended')", name='ck_lessons_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('confusion_signals',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved')", name='ck_confusion_signals_status'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('signal_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_confusion_signals_lesson_status_created', 'confusion_signals', ['lesson_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_confusion_signals_student_id', 'confusion_signals', ['student_id'], unique=False)
    op.create_table('question_clusters',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('representative_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('tutor_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('ai_drafted_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent_individually', 'addressed_to_class')", name='ck_questions_status'),
    sa.ForeignKeyConstraint(['cluster_id'], ['question_clusters.cluster_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('tutor_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender IN ('student', 'ai')", name='ck_tutor_messages_sender'),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_messages')
    op.drop_table('questions')
    op.drop_table('tutor_sessions')
    op.drop_table('question_clusters')
    op.drop_index('ix_confusion_signals_student_id', table_name='confusion_signals')
    op.drop_index('ix_confusion_signals_lesson_status_created', table_name='confusion_signals')
    op.drop_table('confusion_signals')
    op.drop_table('lessons')
    op.drop_index('ix_enrollments_class_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_current_skills_class_topic', table_name='current_skills')
    op.drop_table('current_skills')
    op.drop_table('classes')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('skill_topics')
    # ### end Alembic commands ###
